<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" 
                xmlns:html="http://www.w3.org/TR/REC-html40"
                xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/">
		<html xmlns="http://www.w3.org/1999/xhtml">
			<head>
				<title>XML Sitemap | UnityESS</title>
				<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
				<style type="text/css">
					body {
						font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
						font-size: 14px;
						color: #0d1b3e;
						margin: 0;
						padding: 40px;
						background-color: #f8fafc;
					}
					.container {
						max-width: 1000px;
						margin: 0 auto;
						background: white;
						padding: 40px;
						border-radius: 16px;
						box-shadow: 0 4px 20px rgba(0,0,0,0.05);
					}
					h1 {
						font-size: 32px;
						font-weight: 800;
						margin: 0 0 10px 0;
						letter-spacing: -0.02em;
					}
					p.description {
						color: #64748b;
						margin-bottom: 30px;
						font-size: 16px;
					}
					table {
						width: 100%;
						border-collapse: collapse;
						margin-top: 20px;
					}
					th {
						text-align: left;
						padding: 12px 15px;
						background-color: #f1f5f9;
						font-weight: 700;
						color: #475569;
						text-transform: uppercase;
						font-size: 12px;
						letter-spacing: 0.05em;
					}
					td {
						padding: 15px;
						border-bottom: 1px solid #f1f5f9;
					}
					tr:hover td {
						background-color: #f8fafc;
					}
					a {
						color: #00b853;
						text-decoration: none;
						font-weight: 600;
					}
					a:hover {
						text-decoration: underline;
					}
					.priority-high {
						color: #00b853;
						font-weight: 800;
					}
					.footer {
						margin-top: 40px;
						color: #94a3b8;
						font-size: 12px;
						text-align: center;
					}
				</style>
			</head>
			<body>
				<div class="container">
					<h1>Sitemap</h1>
					<p class="description">This is an XML Sitemap, meant for consumption by search engines. It is styled for human readability.</p>
					<table>
						<thead>
							<tr>
								<th>URL</th>
								<th>Priority</th>
								<th>Change Freq.</th>
								<th>Last Modified (GMT)</th>
							</tr>
						</thead>
						<tbody>
							<xsl:for-each select="sitemap:urlset/sitemap:url">
								<tr>
									<td>
										<xsl:variable name="itemURL">
											<xsl:value-of select="sitemap:loc"/>
										</xsl:variable>
										<a href="{$itemURL}">
											<xsl:value-of select="sitemap:loc"/>
										</a>
									</td>
									<td>
										<xsl:choose>
											<xsl:when test="sitemap:priority &gt;= 0.8">
												<span class="priority-high"><xsl:value-of select="concat(sitemap:priority*100, '%')"/></span>
											</xsl:when>
											<xsl:otherwise>
												<xsl:value-of select="concat(sitemap:priority*100, '%')"/>
											</xsl:otherwise>
										</xsl:choose>
									</td>
									<td>
										<xsl:value-of select="sitemap:changefreq"/>
									</td>
									<td>
										<xsl:value-of select="sitemap:lastmod"/>
									</td>
								</tr>
							</xsl:for-each>
						</tbody>
					</table>
					<div class="footer">
						Generated by UnityESS Sitemap UI. Powered by Next.js.
					</div>
				</div>
			</body>
		</html>
	</xsl:template>
</xsl:stylesheet>
